In [252]:
base_pattern = [0, 1, 0, -1]
bpl = length(base_pattern)
function makepatterns(len)
    patterns = zeros(Int64, len, len)
    for i in 1:len
        for j in 1:len
            patterns[i, j] = base_pattern[(j ÷ i) % length(base_pattern) + 1]
        end
    end
        
    patterns
end
makepatterns(20)

20×20 Array{Int64,2}:
 1  0  -1  0  1   0  -1  0   1   0  -1   0   1   0  -1   0   1   0  -1   0
 0  1   1  0  0  -1  -1  0   0   1   1   0   0  -1  -1   0   0   1   1   0
 0  0   1  1  1   0   0  0  -1  -1  -1   0   0   0   1   1   1   0   0   0
 0  0   0  1  1   1   1  0   0   0   0  -1  -1  -1  -1   0   0   0   0   1
 0  0   0  0  1   1   1  1   1   0   0   0   0   0  -1  -1  -1  -1  -1   0
 0  0   0  0  0   1   1  1   1   1   1   0   0   0   0   0   0  -1  -1  -1
 0  0   0  0  0   0   1  1   1   1   1   1   1   0   0   0   0   0   0   0
 0  0   0  0  0   0   0  1   1   1   1   1   1   1   1   0   0   0   0   0
 0  0   0  0  0   0   0  0   1   1   1   1   1   1   1   1   1   0   0   0
 0  0   0  0  0   0   0  0   0   1   1   1   1   1   1   1   1   1   1   0
 0  0   0  0  0   0   0  0   0   0   1   1   1   1   1   1   1   1   1   1
 0  0   0  0  0   0   0  0   0   0   0   1   1   1   1   1   1   1   1   1
 0  0   0  0  0   0   0  0   0   0   0   0   1   1   1   1   1   1   1   1
 0 

In [212]:
makepatterns(16)[]

4×4 Array{Int64,2}:
 1  0  -1  0
 0  1   1  0
 0  0   1  1
 0  0   0  1

In [145]:
makepatterns(8)

8×8 Array{Int64,2}:
 1  0  -1  0  1   0  -1  0
 0  1   1  0  0  -1  -1  0
 0  0   1  1  1   0   0  0
 0  0   0  1  1   1   1  0
 0  0   0  0  1   1   1  1
 0  0   0  0  0   1   1  1
 0  0   0  0  0   0   1  1
 0  0   0  0  0   0   0  1

In [68]:
function step(v, patterns)
    abs.(patterns * v .% 10)
end
function nsteps(n, init)
    patterns = makepatterns(length(init))
    foldl((x, y) -> step(x, patterns), 1:n, init=init)
end
#step([1,2,3,4,5,6,7,8])
nsteps(4, [1,2,3,4,5,6,7,8])'

1×8 LinearAlgebra.Adjoint{Int64,Array{Int64,1}}:
 0  1  0  2  9  4  9  8

In [62]:
function splitbig(s)
    v = zeros(Int64, length(s))
    for (i, c) in enumerate(s)
        v[i] = parse(Int,c)
    end
    v
end
splitbig("12345")'

1×5 LinearAlgebra.Adjoint{Int64,Array{Int64,1}}:
 1  2  3  4  5

In [60]:
join(splitbig("12345"))

"12345"

In [65]:
join(nsteps(100, splitbig("80871224585914546619083218645595")))[1:8]

"24176176"

In [141]:
input = "59762770781817719190459920638916297932099919336473880209100837309955133944776196290131062991588533604012789279722697427213158651963842941000227675363260513283349562674004015593737518754413236241876959840076372395821627451178924619604778486903040621916904575053141824939525904676911285446889682089563075562644813747239285344522507666595561570229575009121663303510763018855038153974091471626380638098740818102085542924937522595303462725145620673366476987473519905565346502431123825798174326899538349747404781623195253709212209882530131864820645274994127388201990754296051264021264496618531890752446146462088574426473998601145665542134964041254919435635"
inputv = splitbig(input)
v = copy(inputv)
join(nsteps(100, v))[1:8]

"34694616"

In [72]:
makepatterns(length(inputv))

650×650 Array{Int64,2}:
 1  0  -1  0  1   0  -1  0   1   0  -1  …   0  -1   0   1   0  -1  0   1   0
 0  1   1  0  0  -1  -1  0   0   1   1      1   1   0   0  -1  -1  0   0   1
 0  0   1  1  1   0   0  0  -1  -1  -1      0   0   0  -1  -1  -1  0   0   0
 0  0   0  1  1   1   1  0   0   0   0      0   0   1   1   1   1  0   0   0
 0  0   0  0  1   1   1  1   1   0   0      0   0   0   1   1   1  1   1   0
 0  0   0  0  0   1   1  1   1   1   1  …  -1  -1  -1  -1  -1  -1  0   0   0
 0  0   0  0  0   0   1  1   1   1   1     -1  -1   0   0   0   0  0   0   0
 0  0   0  0  0   0   0  1   1   1   1      0   0   0   0   0   0  1   1   1
 0  0   0  0  0   0   0  0   1   1   1     -1  -1  -1  -1  -1  -1  0   0   0
 0  0   0  0  0   0   0  0   0   1   1      0   0   0   0   0   0  0   0   1
 0  0   0  0  0   0   0  0   0   0   1  …   0   0   0   0   0   0  0  -1  -1
 0  0   0  0  0   0   0  0   0   0   0      1   1   1   1   1   1  0   0   0
 0  0   0  0  0   0   0  0   0   0   0      1   1   

In [76]:
@time inputv2 = repeat(inputv, outer=[10000])
length(inputv2)

  0.273884 seconds (40.02 k allocations: 101.924 MiB, 83.62% gc time)


6500000

In [142]:
function nmatrixless(n, v, base_pattern)
    bpl = length(base_pattern)
    outv = zeros(Int64, size(v))
    for ni in 1:n
        for i in 1:length(v)
            outv[i] = 0
            for j in i:length(v)
                outv[i] += base_pattern[(j ÷ i) % bpl + 1] * v[j]
            end
            outv[i] = abs(outv[i] % 10)
        end
        tmp = outv
        outv = v
        v = tmp
    end
    v
end
#function nmatrixless(n, init)
#    foldl((x, y) -> matrixless(x), 1:n, init=init)
#end
v = copy(inputv)
inputv
@time join(nmatrixless(100, v, base_pattern)[1:8])
#@time join(nmatrixless(100, repeat(inputv, outer=[2]), base_pattern))[1:8]
#@time join(nmatrixless(100, repeat(inputv, outer=[3]), base_pattern))[1:8]
v = copy(inputv)
@time join(nmatrixless(100, repeat(v, outer=[10]), base_pattern))[1:8]

  0.205905 seconds (29.06 k allocations: 1.476 MiB)
 15.166119 seconds (13.07 k allocations: 770.766 KiB)


"92166021"

In [143]:
v = copy(inputv)
@time join(nmatrixless(100, repeat(v, outer=[2]), base_pattern))[1:8]

  0.632884 seconds (2.64 k allocations: 154.563 KiB)


"09394701"

In [139]:
function matrixless(n, v, base_pattern)
    bpl = length(base_pattern)
    outv = zeros(Int64, size(v))
    for i in 1:length(v)
        outv[i] = 0
        for j in i:length(v)
            outv[i] += base_pattern[(j ÷ i) % bpl + 1] * v[j]
        end
        outv[i] = abs(outv[i] % 10)
    end
    outv
end
function nmatrixless(n, init)
    foldl((x, y) -> matrixless(x), 1:n, init=init)
end
@time join(nmatrixless(100, inputv, base_pattern)[1:8])
#inputv

  0.185822 seconds (27 allocations: 6.516 KiB)


"34694616"

In [113]:

@time join(nmatrixless(100, repeat(inputv, outer=[3]), base_pattern))[1:8]

  1.400898 seconds (3.94 k allocations: 231.641 KiB)


"88998939"

In [116]:
@time join(nmatrixless(100, inputv, base_pattern)[1:8])


  0.187661 seconds (27 allocations: 6.516 KiB)


"03591228"

In [146]:
@time join(nmatrixless(2, splitbig("1234512345"), base_pattern))

  0.000505 seconds (31 allocations: 1.641 KiB)


"2646550645"

In [109]:
@time join(nmatrixless(2, splitbig("123456781234567812345678"), base_pattern))

  0.000020 seconds (60 allocations: 3.234 KiB)


"244260487188271465306158"

In [250]:
total_steps = 0

function base(n, v, base_pattern, shift)
    bpl = length(base_pattern)
    outv = zeros(Int64, size(v))
    #for i in 1:(n÷2)
    #    outv[i] = 0
    #    for j in i:n
    #        outv[i] += base_pattern[(j÷i+shift) % bpl + 1] * v[j]
    #        global total_steps += 1
    #    end
    #    x = outv[i]
    #    outv[i] = abs(outv[i] % 10)
    #end
    x = 0
    for i in n:-1:(n÷2+1)
        println("i", i)
        x += v[i]
        outv[i] = abs(x % 10)
    end
    outv
end

println(join(base(16, splitbig("12345678123456781234567812345678"), base_pattern, 0)))
println(total_steps, " ", 16 * 16 / 2)

i16
i15
i14
i13
i12
i11
i10
i9
00000000653061580000000000000000
0 128.0


In [196]:
join(matrixless(16, splitbig("1234567812345678"), base_pattern))

"8610270665306158"

In [222]:
base(8, splitbig("12345678"), base_pattern, 8)

8-element Array{Int64,1}:
 4
 8
 2
 2
 6
 1
 5
 8

In [223]:
base(8, splitbig("12345678"), base_pattern, 0)

8-element Array{Int64,1}:
 4
 8
 2
 2
 6
 1
 5
 8

In [219]:
base(8, splitbig("12345678"), base_pattern, 0) .+ base(8, splitbig("12345678"), base_pattern, 8)

8-element Array{Int64,1}:
  8
 16
  4
  4
 12
  2
 10
 16

In [169]:
matrixless(5, splitbig("00005678"), base_pattern)

8-element Array{Int64,1}:
 2
 3
 5
 8
 6
 1
 5
 8

In [183]:
base(5, splitbig("5678"), base_pattern, 4)

4-element Array{Int64,1}:
 0
 0
 0
 0

In [168]:
base(5, splitbig("12345678"), base_pattern)

8-element Array{Int64,1}:
 4
 8
 2
 2
 6
 1
 5
 8